services:
  backend:
    build:
      context: ./back
      dockerfile: docker/Dockerfile
    ports:
      - "5001:5001"
    environment:
      - NODE_ENV=production
      - MONGO_URL=mongodb://mongo:27017/dev
    depends_on:
      - mongo
    volumes:
      - ./back/uploads:/app/uploads
    networks:
      - internal

  frontend:
    build:
      context: ./front
      dockerfile: docker/Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    depends_on:
      - backend
    networks:
      - internal

  mongo:
    image: mongo:latest
    volumes:
      - mongo-data:/data/db
    networks:
      - internal

volumes:
  mongo-data:

networks:
  internal:
    driver: bridge
  